cc_test(
    name = "queue_test",
    size = "small",
    srcs = ["integration_test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//core:core"
    ],
)